# Generated by Django 5.0.7 on 2024-07-31 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0002_user_username_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approval_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('disapproved', 'Disapproved')], default='disapproved', max_length=100, null=True),
        ),
    ]
