# Generated by Django 5.0.7 on 2024-08-06 08:36

import beposoft_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0004_customers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='gst',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[beposoft_app.validators.validate_gst]),
        ),
    ]
