# Generated by Django 5.0.7 on 2024-08-07 11:05

import beposoft_app.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0005_alter_customers_created_at_alter_customers_gst'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Family',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('hsn_code', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('single', 'Single'), ('variant', 'Variant')], default='single', max_length=100)),
                ('unit', models.CharField(choices=[('BOX', 'BOX'), ('NOS', 'NOS'), ('PRS', 'PRS'), ('SET', 'SET'), ('SET OF 12', 'SET OF 12'), ('SET OF 16', 'SET OF 16'), ('SET OF 6', 'SET OF 6'), ('SET OF 8', 'SET OF 8')], default='BOX', max_length=100)),
                ('purchase_rate', models.FloatField()),
                ('tax', models.FloatField()),
                ('exclude_price', models.FloatField()),
            ],
            options={
                'db_table': 'Products',
            },
        ),
        migrations.AlterField(
            model_name='customers',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='gst',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[beposoft_app.validators.validate_gst]),
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('zipcode', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.customers')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.state')),
            ],
            options={
                'db_table': 'Shipping_Address',
            },
        ),
    ]
