# Generated by Django 5.0.7 on 2024-08-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0006_family_products_alter_customers_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='selling_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterModelTable(
            name='products',
            table=None,
        ),
    ]
