# Generated by Django 5.0.7 on 2024-08-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0007_products_selling_price_alter_products_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='exclude_price',
            field=models.FloatField(editable=False),
        ),
    ]
