# Generated by Django 5.0.7 on 2024-08-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0008_alter_products_exclude_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='family',
            field=models.ManyToManyField(null=True, related_name='products', to='beposoft_app.family'),
        ),
    ]
