# Generated by Django 5.0.7 on 2024-08-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0009_products_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='family',
            field=models.ManyToManyField(related_name='products', to='beposoft_app.family'),
        ),
    ]
