# Generated by Django 5.0.7 on 2024-08-12 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0010_alter_products_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='created_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.user'),
        ),
        migrations.AddField(
            model_name='shipping',
            name='created_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.user'),
        ),
        migrations.CreateModel(
            name='SingleProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='images/')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.user')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='single_products', to='beposoft_app.products')),
            ],
            options={
                'db_table': 'single_product',
            },
        ),
        migrations.CreateModel(
            name='VariantProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stock', models.PositiveBigIntegerField()),
                ('price', models.FloatField(default=0)),
                ('image', models.ImageField(upload_to='images/')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.user')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_products', to='beposoft_app.products')),
            ],
            options={
                'db_table': 'variant_product',
            },
        ),
    ]
