# Generated by Django 5.0.7 on 2024-08-16 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0012_alter_variantproducts_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('invoice', models.CharField(max_length=10)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded'), ('Return', 'Return')], default='Pending', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_method', models.CharField(choices=[('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('PayPal', 'PayPal'), ('Razorpay', 'Razorpay'), ('Net Banking', 'Net Banking'), ('Bank Transfer', 'Bank Transfer')], default='Net Banking', max_length=50)),
                ('billing_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.shipping')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.customers')),
                ('manage_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.PositiveIntegerField()),
                ('net_price', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='beposoft_app.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.products')),
            ],
        ),
    ]
