# Generated by Django 5.0.7 on 2024-08-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0013_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='company',
            field=models.CharField(choices=[('MICHEAL IMPORT EXPORT PVT LTD', 'MICHEAL IMPORT EXPORT PVT LTD'), ('BEPOSOFT PVT  LTD', 'BEPOSOFT PVT  LTD')], default='MICHEAL IMPORT EXPORT PVT LTD', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
