# Generated by Django 5.1 on 2024-08-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0014_alter_order_company_alter_order_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='company',
            field=models.CharField(choices=[('MICHEAL IMPORT EXPORT PVT LTD', 'MICHEAL IMPORT EXPORT PVT LTD'), ('BEPOSOFT PVT LTD', 'BEPOSOFT PVT  LTD')], default='MICHEAL IMPORT EXPORT PVT LTD', max_length=100),
        ),
    ]
