# Generated by Django 5.1 on 2024-09-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0016_alter_order_status_alter_orderitem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='allocated_states',
            field=models.ManyToManyField(blank=True, to='beposoft_app.state'),
        ),
    ]
