# Generated by Django 5.1 on 2024-10-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0023_alter_customers_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
