# Generated by Django 5.1 on 2024-10-07 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0024_alter_customers_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.state'),
        ),
    ]
