# Generated by Django 5.1 on 2024-10-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0025_alter_customers_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantproducts',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='variantproducts',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
