# Generated by Django 5.1 on 2024-10-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0026_variantproducts_color_variantproducts_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variantproducts',
            name='image',
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
