# Generated by Django 5.1 on 2024-10-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0027_remove_variantproducts_image_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantproducts',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
