# Generated by Django 5.1 on 2024-10-09 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0028_variantproducts_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variantproducts',
            name='image',
        ),
        migrations.RemoveField(
            model_name='variantproducts',
            name='price',
        ),
        migrations.RemoveField(
            model_name='variantproducts',
            name='size',
        ),
        migrations.AddField(
            model_name='variantproducts',
            name='is_variant',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProductAttributeVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=100)),
                ('stock', models.PositiveBigIntegerField(default=0)),
                ('variant_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.variantproducts')),
            ],
            options={
                'db_table': 'product_attribute_variant',
            },
        ),
        migrations.CreateModel(
            name='VariantImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('variant_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_images', to='beposoft_app.variantproducts')),
            ],
            options={
                'db_table': 'variant_images',
            },
        ),
    ]
