# Generated by Django 5.1 on 2024-10-09 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0029_remove_variantproducts_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattributevariant',
            name='variant_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='beposoft_app.variantproducts'),
        ),
    ]
