# Generated by Django 5.1 on 2024-10-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0030_alter_productattributevariant_variant_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantproducts',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
