# Generated by Django 5.1 on 2024-10-21 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0031_alter_variantproducts_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeposoftCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.user')),
            ],
            options={
                'db_table': 'beposoft_cart',
            },
        ),
    ]
