# Generated by Django 5.1 on 2024-10-21 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0032_beposoftcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='beposoftcart',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.productattributevariant'),
        ),
        migrations.AddField(
            model_name='beposoftcart',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.variantproducts'),
        ),
    ]
