# Generated by Django 5.1 on 2024-10-21 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0033_beposoftcart_size_beposoftcart_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.family'),
        ),
    ]
