# Generated by Django 5.1 on 2024-10-23 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0034_user_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beposoftcart',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.variantproducts'),
        ),
        migrations.AlterField(
            model_name='order',
            name='company',
            field=models.CharField(choices=[('MICHEAL IMPORT EXPORT PVT LTD', 'MICHEAL IMPORT EXPORT PVT LTD'), ('BEPOSITIVERACING PVT LTD', 'BEPOSITIVERACING PVT  LTD')], default='MICHEAL IMPORT EXPORT PVT LTD', max_length=100),
        ),
    ]
