# Generated by Django 5.1 on 2024-10-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0037_orderitem_discount_orderitem_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bank',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
