# Generated by Django 5.1 on 2024-10-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0046_order_code_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_mode',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
