# Generated by Django 5.1 on 2024-10-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0047_order_shipping_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code_charge',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
