# Generated by Django 5.1 on 2024-10-31 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0049_alter_orderitem_discount_alter_orderitem_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='net_price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
