# Generated by Django 5.1 on 2024-10-31 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0050_remove_orderitem_net_price_remove_orderitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.bank'),
        ),
    ]
