# Generated by Django 5.1 on 2024-10-31 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0051_alter_order_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank', to='beposoft_app.bank'),
        ),
    ]
