# Generated by Django 5.1 on 2024-11-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0055_alter_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_charge',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
