# Generated by Django 5.1.2 on 2024-11-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0056_order_shipping_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_mode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
