# Generated by Django 5.1.2 on 2024-11-05 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0058_paymentreceipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentreceipt',
            name='created_at',
        ),
    ]
