# Generated by Django 5.1.2 on 2024-11-06 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0059_remove_paymentreceipt_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentreceipt',
            name='received_at',
            field=models.DateField(),
        ),
    ]
