# Generated by Django 5.1.2 on 2024-11-07 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0060_alter_paymentreceipt_received_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Shipped', 'Shipped'), ('Invoice Created', 'Invoice Created'), ('Invoice Approved', 'Invoice Approved'), ('Waiting For Confirmation', 'Waiting For Confirmation'), ('To Print', 'To Print'), ('Invoice Rejectd', 'Invoice Rejectd'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded'), ('Return', 'Return')], default='Pending', max_length=100),
        ),
    ]
