# Generated by Django 5.1.2 on 2024-11-07 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0062_order_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceipt',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.customers'),
        ),
    ]
