# Generated by Django 5.1.2 on 2024-11-09 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0063_paymentreceipt_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfomaInvoiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(choices=[('MICHEAL IMPORT EXPORT PVT LTD', 'MICHEAL IMPORT EXPORT PVT LTD'), ('BEPOSITIVERACING PVT LTD', 'BEPOSITIVERACING PVT  LTD')], default='MICHEAL IMPORT EXPORT PVT LTD', max_length=100)),
                ('invoice', models.CharField(blank=True, max_length=20, unique=True)),
                ('order_date', models.CharField(max_length=100)),
                ('code_charge', models.IntegerField(default=0, null=True)),
                ('shipping_mode', models.CharField(max_length=100, null=True)),
                ('shipping_charge', models.IntegerField(default=0, null=True)),
                ('payment_status', models.CharField(choices=[('payed', 'payed'), ('COD', 'COD'), ('credit', 'credit')], default='payed', max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Shipped', 'Shipped'), ('Invoice Created', 'Invoice Created'), ('Invoice Approved', 'Invoice Approved'), ('Waiting For Confirmation', 'Waiting For Confirmation'), ('To Print', 'To Print'), ('Invoice Rejectd', 'Invoice Rejectd'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded'), ('Return', 'Return')], default='Pending', max_length=100)),
                ('total_amount', models.FloatField()),
                ('note', models.TextField(null=True)),
                ('payment_method', models.CharField(choices=[('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('PayPal', 'PayPal'), ('Razorpay', 'Razorpay'), ('Net Banking', 'Net Banking'), ('Bank Transfer', 'Bank Transfer'), ('Cash on Delivery', 'Cash on Delivery')], default='Net Banking', max_length=50)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfoma_bank', to='beposoft_app.bank')),
                ('billing_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfoma_billing_address', to='beposoft_app.shipping')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfoma_customer', to='beposoft_app.customers')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.family')),
                ('manage_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.user')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.state')),
            ],
        ),
        migrations.CreateModel(
            name='PerfomaInvoiceOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, null=True)),
                ('rate', models.IntegerField()),
                ('tax', models.PositiveIntegerField()),
                ('discount', models.IntegerField(default=0, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfoma_items', to='beposoft_app.perfomainvoiceorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.products')),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.productattributevariant')),
                ('variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.variantproducts')),
            ],
        ),
    ]
