# Generated by Django 5.1.2 on 2024-11-12 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0064_perfomainvoiceorder_perfomainvoiceorderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gst', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=500, null=True)),
                ('zip', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('web_site', models.URLField()),
                ('prefix', models.CharField(help_text='Unique prefix for invoice numbers', max_length=5, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.company'),
        ),
    ]
