# Generated by Django 5.1.3 on 2024-11-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0066_expensemodel_grvmodel_warehousedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grvmodel',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
