# Generated by Django 5.1.3 on 2024-11-27 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0067_alter_grvmodel_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousedata',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse', to='beposoft_app.order'),
        ),
    ]
