# Generated by Django 5.1.3 on 2024-11-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0069_alter_warehousedata_shipping_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousedata',
            name='parcel_service',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
