# Generated by Django 5.1.3 on 2024-11-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0070_alter_warehousedata_parcel_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousedata',
            name='shipped_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
