# Generated by Django 5.1.3 on 2024-12-03 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0071_alter_warehousedata_shipped_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousedata',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.bank'),
        ),
    ]
