# Generated by Django 5.1.3 on 2024-12-04 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0072_warehousedata_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'parcal_service',
            },
        ),
        migrations.AlterField(
            model_name='warehousedata',
            name='parcel_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.parcalservice'),
        ),
    ]
