# Generated by Django 5.1.3 on 2024-12-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0073_parcalservice_alter_warehousedata_parcel_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousedata',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
