# Generated by Django 5.1.3 on 2024-12-18 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0078_products_color_products_groupid_products_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beposoftcart',
            name='size',
        ),
        migrations.RemoveField(
            model_name='beposoftcart',
            name='variant',
        ),
    ]
