# Generated by Django 5.1.3 on 2024-12-18 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0079_remove_beposoftcart_size_remove_beposoftcart_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfomainvoiceorderitem',
            name='size',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='size',
        ),
        migrations.RemoveField(
            model_name='variantimages',
            name='variant_product',
        ),
        migrations.RemoveField(
            model_name='variantproducts',
            name='created_user',
        ),
        migrations.RemoveField(
            model_name='variantproducts',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='perfomainvoiceorderitem',
            name='variant',
        ),
        migrations.AlterField(
            model_name='singleproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='beposoft_app.products'),
        ),
        migrations.DeleteModel(
            name='ProductAttributeVariant',
        ),
        migrations.DeleteModel(
            name='VariantImages',
        ),
        migrations.DeleteModel(
            name='VariantProducts',
        ),
    ]
