# Generated by Django 5.1.3 on 2024-12-30 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0080_remove_perfomainvoiceorderitem_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conpanies', to='beposoft_app.company'),
        ),
    ]
