# Generated by Django 5.1.3 on 2025-01-03 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0083_alter_beposoftcart_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentreceipt',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recived_payment', to='beposoft_app.order'),
        ),
    ]
