# Generated by Django 5.1.3 on 2025-01-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0086_alter_order_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='alt_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
