# Generated by Django 5.1.3 on 2025-01-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0087_alter_customers_alt_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
