# Generated by Django 5.1.3 on 2025-01-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0088_alter_customers_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensemodel',
            name='purpose_of_payment',
            field=models.CharField(choices=[('water', 'Water'), ('electricity', 'Electricity'), ('salary', 'Salary'), ('emi', 'EMI'), ('rent', 'Rent'), ('equipments,', 'Equipments'), ('travel', 'Travel'), ('others', 'Others')], max_length=100, null=True),
        ),
    ]
