# Generated by Django 5.1.3 on 2025-01-18 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0089_alter_expensemodel_purpose_of_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='WareHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('unique_id', models.CharField(blank=True, max_length=10, null=True, unique=True)),
            ],
        ),
    ]
