# Generated by Django 5.1.3 on 2025-01-18 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0090_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='warehouse_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='beposoft_app.warehouse'),
        ),
    ]
