# Generated by Django 5.1.3 on 2025-01-18 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0091_user_warehouse_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='beposoft_app.warehouse'),
        ),
    ]
