# Generated by Django 5.1.3 on 2025-01-20 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0093_orderrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='source_warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_orders', to='beposoft_app.warehouse'),
        ),
        migrations.AddField(
            model_name='order',
            name='target_warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_orders', to='beposoft_app.warehouse'),
        ),
    ]
