# Generated by Django 5.1.3 on 2025-01-20 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0094_order_source_warehouse_order_target_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='source_warehouse',
        ),
        migrations.RemoveField(
            model_name='order',
            name='target_warehouse',
        ),
    ]
