# Generated by Django 5.1.3 on 2025-01-20 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0095_remove_order_source_warehouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='warehouses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.warehouse'),
        ),
    ]
