# Generated by Django 5.1.3 on 2025-01-21 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0099_alter_attendance_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='status',
            new_name='status1',
        ),
    ]
