# Generated by Django 5.1.3 on 2025-01-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0102_rename_status_attendance_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='landing_cost',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='retail_price',
            field=models.FloatField(null=True),
        ),
    ]
