# Generated by Django 5.1.3 on 2025-01-22 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0103_products_landing_cost_products_retail_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='selling_price',
        ),
    ]
