# Generated by Django 5.1.3 on 2025-01-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0104_remove_products_selling_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='selling_price',
            field=models.FloatField(null=True),
        ),
    ]
