# Generated by Django 5.1.3 on 2025-01-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0105_products_selling_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='landing_cost',
            field=models.FloatField(null=True),
        ),
    ]
