# Generated by Django 5.1.3 on 2025-01-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0107_alter_products_selling_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
