# Generated by Django 5.1.3 on 2025-01-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0109_alter_paymentreceipt_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousedata',
            name='actual_weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='warehousedata',
            name='parcel_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
