# Generated by Django 5.1.3 on 2025-01-29 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0110_warehousedata_actual_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousedata',
            name='postoffice_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
