# Generated by Django 5.1.3 on 2025-01-30 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0111_warehousedata_postoffice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.state'),
        ),
    ]
