# Generated by Django 5.1.3 on 2025-01-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0112_alter_customers_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='zip_code',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
