# Generated by Django 5.1.3 on 2025-01-30 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0113_alter_customers_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.state'),
        ),
    ]
