# Generated by Django 5.1.3 on 2025-01-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0114_alter_shipping_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='zipcode',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
