# Generated by Django 5.1.3 on 2025-01-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0115_alter_shipping_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='province',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
