# Generated by Django 5.1.3 on 2025-01-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0116_state_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'paid'), ('COD', 'COD'), ('credit', 'credit'), ('pending', 'pending')], default='paid', max_length=20),
        ),
    ]
