# Generated by Django 5.1.3 on 2025-01-31 11:38

import beposoft_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0120_alter_customers_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='gst',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[beposoft_app.validators.validate_gst]),
        ),
    ]
