# Generated by Django 5.1.3 on 2025-01-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0121_alter_customers_gst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Shipped', 'Shipped'), ('Invoice Created', 'Invoice Created'), ('Invoice Approved', 'Invoice Approved'), ('Waiting For Confirmation', 'Waiting For Confirmation'), ('To Print', 'To Print'), ('Invoice Rejectd', 'Invoice Rejectd'), ('Order Request by Warehouse', 'Order Request by Warehouse'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded'), ('Rejected', 'Rejected'), ('Return', 'Return')], default='PENDING', max_length=100),
        ),
    ]
