# Generated by Django 5.1.3 on 2025-01-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0123_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'paid'), ('COD', 'COD'), ('credit', 'credit'), ('PENDING', 'PENDING')], default='paid', max_length=20),
        ),
    ]
