# Generated by Django 5.1.3 on 2025-02-01 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0124_alter_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'paid'), ('COD', 'COD'), ('credit', 'credit'), ('PENDING', 'PENDING'), ('VOIDED', 'VOIDED')], default='paid', max_length=20),
        ),
    ]
