# Generated by Django 5.1.3 on 2025-02-01 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0125_alter_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
