# Generated by Django 5.1.3 on 2025-02-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0130_alter_customers_email_alter_customers_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='customer_status',
            field=models.CharField(choices=[('customer', 'customer'), ('warehouse', 'warehouse')], default='customer', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='web_site',
            field=models.URLField(null=True),
        ),
    ]
