# Generated by Django 5.1.3 on 2025-02-07 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0131_customers_customer_status_alter_company_web_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='phone',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
