# Generated by Django 5.1.3 on 2025-02-20 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0135_remove_perfomainvoiceorder_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfomainvoiceorder',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='perfomainvoiceorder',
            name='payment_status',
        ),
    ]
