# Generated by Django 5.1.3 on 2025-02-24 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0136_remove_perfomainvoiceorder_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('stock', models.PositiveBigIntegerField(default=0, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('is_variant', models.BooleanField(default=False)),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.user')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_products', to='beposoft_app.products')),
            ],
            options={
                'db_table': 'variant_product',
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.variantproducts'),
        ),
    ]
