# Generated by Django 5.1.3 on 2025-02-24 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0137_variantproducts_orderitem_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttributeVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=100)),
                ('stock', models.PositiveBigIntegerField(default=0)),
                ('variant_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='beposoft_app.variantproducts')),
            ],
            options={
                'db_table': 'product_attribute_variant',
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.productattributevariant'),
        ),
    ]
