# Generated by Django 5.1.3 on 2025-02-24 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0138_productattributevariant_orderitem_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('variant_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_images', to='beposoft_app.variantproducts')),
            ],
            options={
                'db_table': 'variant_images',
            },
        ),
    ]
