# Generated by Django 5.1.3 on 2025-02-27 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0140_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='purchase_type',
            field=models.CharField(choices=[('Local', 'Local'), ('International', 'International')], default='International', max_length=100),
        ),
    ]
