# Generated by Django 5.1.3 on 2025-02-27 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0142_products_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_approved_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_products', to='beposoft_app.user'),
        ),
    ]
