# Generated by Django 5.1.3 on 2025-02-27 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0143_products_product_approved_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousedata',
            name='verified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verified_user', to='beposoft_app.user'),
        ),
    ]
