# Generated by Django 5.1.3 on 2025-02-27 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0144_warehousedata_verified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousedata',
            name='checked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_user', to='beposoft_app.user'),
        ),
    ]
