# Generated by Django 5.1.3 on 2025-03-04 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepocart', '0004_alter_loan_user'),
        ('beposoft_app', '0145_warehousedata_checked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensemodel',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_expenses', to='bepocart.loan'),
        ),
    ]
