# Generated by Django 5.1.3 on 2025-03-04 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0146_expensemodel_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensemodel',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='beposoft_app.bank'),
        ),
        migrations.AlterField(
            model_name='expensemodel',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='beposoft_app.company'),
        ),
        migrations.AlterField(
            model_name='expensemodel',
            name='payed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='beposoft_app.user'),
        ),
        migrations.AlterField(
            model_name='expensemodel',
            name='purpose_of_payment',
            field=models.CharField(choices=[('water', 'Water'), ('electricity', 'Electricity'), ('salary', 'Salary'), ('emi', 'EMI'), ('rent', 'Rent'), ('equipments', 'Equipments'), ('travel', 'Travel'), ('others', 'Others')], max_length=100, null=True),
        ),
    ]
