# Generated by Django 5.1.3 on 2025-03-04 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0148_remove_expensemodel_loan_alter_expensemodel_bank_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpenseModel',
        ),
    ]
