# Generated by Django 5.1.3 on 2025-03-07 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0149_delete_expensemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfomainvoiceorderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='perfomainvoiceorderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='PerfomaInvoiceOrder',
        ),
        migrations.DeleteModel(
            name='PerfomaInvoiceOrderItem',
        ),
    ]
