# Generated by Django 5.1.3 on 2025-03-07 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0149_delete_expensemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfomainvoiceorder',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.company'),
        ),
    ]
