# Generated by Django 5.1.3 on 2025-03-07 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0150_remove_perfomainvoiceorderitem_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfomaInvoiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.CharField(blank=True, max_length=20, unique=True)),
                ('order_date', models.CharField(max_length=100)),
                ('code_charge', models.IntegerField(default=0, null=True)),
                ('shipping_mode', models.CharField(max_length=100, null=True)),
                ('shipping_charge', models.IntegerField(default=0, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Shipped', 'Shipped'), ('Invoice Created', 'Invoice Created'), ('Invoice Approved', 'Invoice Approved'), ('Waiting For Confirmation', 'Waiting For Confirmation'), ('To Print', 'To Print'), ('Invoice Rejected', 'Invoice Rejected'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded'), ('Return', 'Return')], default='Pending', max_length=100)),
                ('total_amount', models.FloatField()),
                ('note', models.TextField(null=True)),
                ('billing_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfoma_billing_address', to='beposoft_app.shipping')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfoma_companies', to='beposoft_app.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfoma_customer', to='beposoft_app.customers')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.family')),
                ('manage_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.user')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.state')),
                ('warehouses_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.warehouse')),
            ],
        ),
    ]
