# Generated by Django 5.1.3 on 2025-03-07 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0150_alter_perfomainvoiceorder_company'),
        ('beposoft_app', '0152_perfomainvoiceorderitem'),
    ]

    operations = [
    ]
