# Generated by Django 5.1.3 on 2025-03-11 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0153_merge_20250307_1316'),
        ('beposoft_app', '0154_alter_perfomainvoiceorder_company'),
    ]

    operations = [
    ]
