# Generated by Django 5.1.3 on 2025-03-17 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0156_order_cod_amount_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousedata',
            name='message_status',
            field=models.CharField(choices=[('pending', 'pending'), ('sent', 'sent')], default='pending', max_length=30),
        ),
    ]
