# Generated by Django 5.1.3 on 2025-03-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0157_warehousedata_message_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_mode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
