# Generated by Django 5.1.3 on 2025-03-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0158_alter_order_shipping_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='locked_stock',
            field=models.IntegerField(default=0),
        ),
    ]
