# Generated by Django 5.1.3 on 2025-03-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0159_products_locked_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='exclude_price',
            field=models.FloatField(default=0.0, editable=False),
        ),
    ]
