# Generated by Django 5.1.3 on 2025-02-28 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepocart', '0001_initial'),
        ('beposoft_app', '0140_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.user'),
        ),
    ]
