# Generated by Django 5.1.3 on 2025-03-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepocart', '0002_loan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='emi_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
