# Generated by Django 5.1.3 on 2025-03-04 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepocart', '0004_alter_loan_user'),
        ('beposoft_app', '0148_remove_expensemodel_loan_alter_expensemodel_bank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='emi_name',
        ),
        migrations.AlterField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.user'),
        ),
    ]
