# Generated by Django 5.1.3 on 2025-03-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepocart', '0005_remove_loan_emi_name_alter_loan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='emi_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
