# Generated by Django 5.1.3 on 2025-03-04 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepocart', '0006_loan_emi_name'),
        ('beposoft_app', '0149_delete_expensemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose_of_payment', models.CharField(choices=[('water', 'Water'), ('electricity', 'Electricity'), ('salary', 'Salary'), ('emi', 'EMI'), ('rent', 'Rent'), ('equipments,', 'Equipments'), ('travel', 'Travel'), ('others', 'Others')], max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('expense_date', models.DateField()),
                ('transaction_id', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('added_by', models.CharField(max_length=30, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='beposoft_app.bank')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='beposoft_app.company')),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_expenses', to='bepocart.loan')),
                ('payed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payed_by', to='beposoft_app.user')),
            ],
        ),
    ]
