# Generated by Django 5.1.3 on 2025-03-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepocart', '0007_expensemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='enddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='startdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
