# Generated by Django 5.1.3 on 2025-03-04 10:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepocart', '0009_expensemodel_name_expensemodel_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='emi_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculated EMI amount', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='total_interest',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total interest payable over the tenure', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='total_payment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total payment (principal + interest)', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='tenure_months',
            field=models.IntegerField(help_text='Loan duration in months', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
