# Generated by Django 5.1.3 on 2025-03-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepocart', '0010_loan_emi_amount_loan_total_interest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensemodel',
            name='asset_types',
            field=models.CharField(choices=[('assets', 'assets'), ('expenses', 'expenses')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expensemodel',
            name='purpose_of_payment',
            field=models.CharField(choices=[('water', 'Water'), ('electricity', 'Electricity'), ('salary', 'Salary'), ('emi', 'EMI'), ('rent', 'Rent'), ('equipments,', 'Equipments'), ('travel', 'Travel'), ('others', 'Others'), ('Other assets', 'Other assets')], max_length=100, null=True),
        ),
    ]
