# Generated by Django 5.1.3 on 2025-03-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepocart', '0011_expensemodel_asset_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='emi_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculated EMI amount', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='total_interest',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total interest payable over the tenure', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='total_payment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total payment (principal + interest)', max_digits=20, null=True),
        ),
    ]
