# Generated by Django 5.1.3 on 2025-03-06 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepocart', '0013_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensemodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bepocart.category'),
        ),
    ]
