# Generated by Django 5.1.3 on 2025-03-06 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bepocart', '0014_expensemodel_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
    ]
