# Generated by Django 5.1.3 on 2025-03-07 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bepocart', '0015_rename_name_category_category_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpenseModel',
        ),
    ]
