# Generated by Django 5.1.3 on 2025-03-07 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bepocart', '0017_purpose'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Purpose',
            new_name='Choices',
        ),
    ]
