# Generated by Django 5.1.3 on 2025-03-07 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bepocart', '0018_rename_purpose_choices'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choices',
        ),
    ]
