# Generated by Django 5.1.3 on 2025-03-07 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepocart', '0020_choices'),
        ('beposoft_app', '0154_alter_perfomainvoiceorder_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('expense_date', models.DateField()),
                ('transaction_id', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('added_by', models.CharField(max_length=30, null=True)),
                ('asset_types', models.CharField(choices=[('assets', 'Assets'), ('expenses', 'Expenses')], max_length=100, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='beposoft_app.bank')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bepocart.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='beposoft_app.company')),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_expenses', to='bepocart.loan')),
                ('payed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payed_by', to='beposoft_app.user')),
                ('purpose_of_payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='bepocart.choices')),
            ],
        ),
    ]
